### PR TITLE
Issue 1

### PR DESCRIPTION
**Pull request by scharlton2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scharlton2** [comment]
@conda-forge-admin, please rerender

**Comment by scharlton2** [comment]
@conda-forge-admin, please rerender

**Comment by scharlton2** [comment]
Artifacts can be downloaded from the azure pipeline and tested using the following:

https://conda-forge.org/docs/maintainer/knowledge_base/#local-testing

https://conda-forge.org/docs/maintainer/updating_pkgs/#testing-changes-locally

**Comment by scharlton2** [comment]
@conda-forge-admin, please ping team

**Comment by scharlton2** [comment]
Not trying to be annoying but we're trying to use this package in a class next week.

**Comment by cofinoa** [comment]
Dear @scharlton2, thank you for this. 

You made same approach as I was having in mind.

**Pull request merged**
